version: '1.0'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /usr/futabario/apps/redis/datadir:/data
      - /usr/futabario/apps/redis/conf/redis.conf:/conf/redis.conf
      - /usr/futabario/apps/redis/logs:/logs