version: '3'

services:
  redis:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
